In [2]:
import numpy as np
import cvxpy as cp

In [4]:
A = np.array([[1, 2, 0, 1], [0, 0, 3, 1], [0, 3, 1, 1], [2, 1, 2, 5], [1, 0, 3, 2]])
b = np.ones(5) * 100
p = np.array([3, 2, 7, 6])
d = np.array([2, 1, 4, 2])
q = np.array([4, 10, 5, 10])

**LP formulation**


In [8]:
t, x = cp.Variable(4), cp.Variable(4)
obj = cp.Maximize((p - d).T @ t + d.T @ x)
cons = [0 <= t, t <= q, x >= t, A @ x <= b]

prob = cp.Problem(obj, cons)
prob.solve()

(prob.status, prob.value, t.value, x.value)

('optimal',
 np.float64(192.49999999953474),
 array([ 4. , 10. ,  5. ,  1.5]),
 array([ 4.        , 22.49999999, 31.        ,  1.5       ]))

In [27]:
tstar, xstar = t.value, x.value
[round(d[i] * xstar[i] + (p - d)[i] * tstar[i], 1) for i in range(4)]
[(d[i] * xstar[i] + (p - d)[i] * tstar[i]) / xstar[i] for i in range(4)]

[np.float64(3.0000000080425013),
 np.float64(1.444444447044384),
 np.float64(4.483870968310881),
 np.float64(5.999999860211607)]

**Original formulation**


In [17]:
x = cp.Variable(4)
# this is convex + concave = not recognized
# rev = p.T @ cp.minimum(x, q) + d.T @ cp.maximum(x - q, 0)
rev = d.T @ x + (p - d).T @ cp.minimum(x, q)
obj = cp.Maximize(rev)
cons = [A @ x <= b, x >= 0]

prob = cp.Problem(obj, cons)
prob.solve()
(prob.status, prob.value, x.value)

('optimal',
 np.float64(192.4999999513989),
 array([ 3.99999997, 22.49999987, 30.99999997,  1.50000005]))